version: '3.8'

services:
  crm_api:
    build:
      context: . 
      dockerfile: ./crm_api/Dockerfile 
    ports:
      - "8000:80"
    volumes:
      - ./crm_api/app:/code/app
    container_name: crm_api

  inventory_api:
    build:
      context: . 
      dockerfile: ./inventory_api/Dockerfile 
    ports:
      - "8001:80"
    volumes:
      - ./inventory_api/app:/code/app
    container_name: inventory_api

  integration_service:
    build:
      context: . 
      dockerfile: ./integration_service/Dockerfile 
    environment:
      - CRM_API_URL=http://crm_api/customers
      - INVENTORY_API_URL=http://inventory_api/package-requests
      - POLLING_INTERVAL_SECONDS=10
    depends_on:
      - crm_api
      - inventory_api
    volumes:
      - ./integration_service/service:/code/service
    container_name: integration_service